import type { MapLocation } from "./map-zoom";

/**
 * Generated by scripts/generate-map.ts — do not edit by hand.
 * Re-run: bun run generate-map
 *
 * x/y: marker position as % of the SVG viewBox (0-100).
 * These align with the coastline because they use the same D3 projection.
 */
export const locations: MapLocation[] = [
  {
    "id": "rvk",
    "name": "Reykjavík",
    "label": "Höfuðborg",
    "info": "Norðurljós borgarinnar, þar sem skapandi menning og náttúra mætast.",
    "x": 30.07,
    "y": 74.84
  },
  {
    "id": "tmk",
    "name": "Þórsmörk",
    "label": "Dalur",
    "info": "Falinn dalur milli jökla, vafinn birki og villtum blómum.",
    "x": 46.56,
    "y": 87.68
  },
  {
    "id": "jkl",
    "name": "Jökulsárlón",
    "label": "Jökullón",
    "info": "Ísmoldur reka á lóninu þar sem jökull og sjór mætast.",
    "x": 69.29,
    "y": 76.68
  },
  {
    "id": "lml",
    "name": "Landmannalaugar",
    "label": "Hálendi",
    "info": "Litríkar líparitfjöll og heitar laugar í hjarta hálendisins.",
    "x": 49.62,
    "y": 79.45
  },
  {
    "id": "snf",
    "name": "Snæfellsjökull",
    "label": "Jökuleldfjall",
    "info": "Jökullinn sem Jules Verne valdi sem hlið inn í jörðina.",
    "x": 17.63,
    "y": 56.21
  },
  {
    "id": "aku",
    "name": "Akureyri",
    "label": "Norðurland",
    "info": "Höfuðborg norðursins, umkringd fjöllum og Eyjafjörður.",
    "x": 56.22,
    "y": 31.07
  },
  {
    "id": "myt",
    "name": "Mývatn",
    "label": "Eldfjallahérað",
    "info": "Jarðhitasvæði og lághitaeldfjöll við norðurhöf.",
    "x": 63.98,
    "y": 33.41
  }
];
